PythonMoora/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from app.config import setting
from login import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^login/', include('login.urls', namespace='login')),
    # url(r'^', views.LoginView.as_view(), name='login'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^dologin/$', views.AksiLoginView.as_view(), name='dologin'),
    url(r'^dologout/$', views.AksiLogoutView.as_view(), name='dologout'),

    url(r'^siswa/', include('management.siswa.urls', namespace='siswa')),
    url(r'^kelas/', include('management.kelas.urls', namespace='kelas')),
    url(r'^bobot/', include('management.bobot.urls', namespace='bobot')),
    url(r'^hasiltes/', include('management.hasiltes.urls', namespace='hasiltes')),
    url(r'^nilai_akademik/', include('management.nilai_akademik.urls', namespace='nilai_akademik')),
    url(r'^karakter/', include('management.karakter.urls', namespace='karakter')),
    url(r'^plomba/', include('management.plomba.urls', namespace='plomba')),
    url(r'^hasil_akhir/', include('management.hasil_akhir.urls', namespace='hasil_akhir')),
    url(r'^tesolimpiade/', include('tesolimpiade.urls', namespace='tesolimpiade')),


]

urlpatterns +=  staticfiles_urlpatterns()
urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

PythonMoora/management/hasil_akhir/urls.py
from django.conf.urls import url
from management.hasil_akhir import views

urlpatterns = [
    url (r'^$', views.ListMataPelajaranView.as_view(), name='view'),
    url (r'^fisika$', views.ListFisikaView.as_view(), name='fisika'),
    url (r'^biologi$', views.ListBiologiView.as_view(), name='biologi'),
    url (r'^kimia$', views.ListKimiaView.as_view(), name='kimia'),
    url (r'^matematika$', views.ListMatematikaView.as_view(), name='matematika'),
   

    # Report
    url (r'^reporttbl$', views.GeneratePDFtbl.as_view(), name='reporttbl'),
    url (r'^reportnilai_awal$', views.GeneratePDFnilai_awal.as_view(), name='reportnilai_awal'),
    url (r'^report_pembobotan$', views.GeneratePDFpembobotan.as_view(), name='report_pembobotan'),
    url (r'^report_rangking$', views.GeneratePDFrangking.as_view(), name='report_rangking'),

]

PythonMoora/management/hasil_akhir/models.py
from django.db import models

# Create your models here.

PythonMoora/management/hasil_akhir/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.views.generic import View
from django.http import HttpResponse
from django.contrib import messages
from orm.models import Karakter,NilaiAkademik,HasilTes,Siswa,Plomba,Kelas
from management.hasil_akhir import helpers
from reportlab.pdfgen import canvas
from django.template.loader import get_template

# Create your views here.


class ListMataPelajaranView(View):
    def get(self, request):
        template = 'hasil_akhir/index.html'
     
        return render(request, template)

class ListBiologiView(View):
    def get(self, request):
        template = 'hasil_akhir/biologi.html'
        sw = Siswa.objects.all()
        nl = helpers.Matrix_DataAwalBio(sw).as_matrix()
        data = {
            'data_awal' : nl,
            'ternormalisasi': helpers.Matrix_TernormalisasiBio(sw).as_matrix(),
            'pembobotan': helpers.Matrix_PembobotanBio(sw).as_matrix(),
            'akhir': helpers.Hasil_AkhirBio(sw).as_matrix(),

        }
        return render(request, template, data)

class ListFisikaView(View):
    def get(self, request):
        template = 'hasil_akhir/fisika.html'
        sw = Siswa.objects.all()
        nl = helpers.Matrix_DataAwalFis(sw).as_matrix()
        data = {
            'data_awal' : nl,
            'ternormalisasi': helpers.Matrix_TernormalisasiFis(sw).as_matrix(),
            'pembobotan': helpers.Matrix_PembobotanFis(sw).as_matrix(),
            'akhir': helpers.Hasil_AkhirFis(sw).as_matrix(),

        }
        return render(request, template, data)

class ListKimiaView(View):
    def get(self, request):
        template = 'hasil_akhir/kimia.html'
        sw = Siswa.objects.all()
        nl = helpers.Matrix_DataAwalKim(sw).as_matrix(),
        data = {
            'data_awal' : nl,
            'ternormalisasi': helpers.Matrix_TernormalisasiKim(sw).as_matrix(),
            'pembobotan': helpers.Matrix_PembobotanKim(sw).as_matrix(),
            'akhir': helpers.Hasil_AkhirKim(sw).as_matrix(),

        }
        return render(request, template, data)

class ListMatematikaView(View):
    def get(self, request):
        template = 'hasil_akhir/matematika.html'
        sw = Siswa.objects.all()
        nl = helpers.Matrix_DataAwalMat(sw).as_matrix()
        data = {
            'data_awal' : nl,
            'ternormalisasi': helpers.Matrix_TernormalisasiMat(sw).as_matrix(),
            'pembobotan': helpers.Matrix_PembobotanMat(sw).as_matrix(),
            'akhir': helpers.Hasil_AkhirMat(sw).as_matrix(),

        }
        return render(request, template, data)



        # view untuk Report
        
class GeneratePDFtbl(View):
    def get(self, request, *args, **kwargs):
        template = get_template('hasil_akhir/reporttbl.html')
        sw = Siswa.objects.all()
        nl = helpers.Matrix_TernormalisasiBio().as_matrix()
        data = {
            'nl' : nl,
        }
        html = template.render(data)
        pdf = helpers.render_to_pdf('hasil_akhir/reporttbl.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

class GeneratePDFnilai_awal(View):
    def get(self, request, *args, **kwargs):
        template = get_template('hasil_akhir/reportnilai_awal.html')
        sw = Siswa.objects.all()
        nl = helpers.Matrix_DataAwalBio().as_matrix()
        data = {
            'nl' : nl,
        }
        html = template.render(data)
        pdf = helpers.render_to_pdf('hasil_akhir/reportnilai_awal.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

class GeneratePDFpembobotan(View):
    def get(self, request, *args, **kwargs):
        template = get_template('hasil_akhir/report_pembobotan.html')
        sw = Siswa.objects.all()
        nl = helpers.Matrix_PembobotanBio().as_matrix()
        data = {
            'nl' : nl,
        }
        html = template.render(data)
        pdf = helpers.render_to_pdf('hasil_akhir/report_pembobotan.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

class GeneratePDFrangking(View):
    def get(self, request, *args, **kwargs):
        template = get_template('hasil_akhir/report_rangking.html')
        sw = Siswa.objects.all()
        nl = helpers.Hasil_AkhirBio().as_matrix()
        data = {
            'nl' : nl,
        }
        html = template.render(data)
        pdf = helpers.render_to_pdf('hasil_akhir/report_rangking.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

PythonMoora/management/hasil_akhir/templates/hasil_akhir/biologi.html
<div class="header text-center">
  <h3 class="title">Hasil Sleksi Olimpide Sains</h3>
  <p class="category">Kategori Mata Pelajaran <a>Biologi</a></p>
</div>
<ul class="nav nav-pills nav-stacked">
  <div class="row">
  <div class="col-md-3">
 <li role="presentation">

  
    <a  class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-caret-square-o-down"></i> Matrix Awal </a>
  </li>
  </div>
  
</div>
 
  <div class="collapse" id="collapseExample">
    <div class="well">

     <div align="right">
      <a href="{% url 'hasil_akhir:reporttbl' %}">
       <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
     </a>
   </div>
   <hr>
   <table id="example" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Nilai Akademik</th>
        <th>Karakter</th>
        <th>Pengalaman Lomba</th>
        <th>Hasil Tes</th>
        <th>Kelas</th>
      </tr>
    </thead>
    <tbody>
      {% for c in data_awal %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{c.0}}</td>
        <td>{{c.1}}</td>
        <td>{{c.2}}</td>
        <td>{{c.3}}</td>
        <td>{{c.4}}</td>
        <td>{{c.5}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
</div>  
<!-- ###################################################################### -->
<br>
<div class="row">
  <div class="col-md-3">
<li role="presentation"><a class="btn btn-block btn-social btn-facebook"  type="button" data-toggle="collapse" data-target="#collapseExample1" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-caret-square-o-down"></i>Matrix Ternormalisasi</a></li>    
  </div>
</div>
<div class="collapse" id="collapseExample1">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Nama</th>
      <th>Nilai Akademik</th>
      <th>Karakter</th>
      <th>Pengalaman Lomba</th>
      <th>Hasil Tes</th>
      <th>Kelas</th>
    </tr>
  </thead>
  <tbody>
    {% for c in ternormalisasi %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{c.0}}</td>
      <td>{{c.1}}</td>
      <td>{{c.2}}</td>
      <td>{{c.3}}</td>
      <td>{{c.4}}</td>
      <td>{{c.5}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
</div>
<br>  
<div class="row">
  <div class="col-md-3">
<li role="presentation"><a  class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-caret-square-o-down"></i>Matrix Pembobotan</a></li>    
  </div>
</div>

<div class="collapse" id="collapseExample2">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Nama</th>
      <th>Nilai Akademik</th>
      <th>Karakter</th>
      <th>Pengalaman Lomba</th>
      <th>Hasil Tes</th>
      <th>Kelas</th>
    </tr>
  </thead>
  <tbody>
    {% for c in pembobotan %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{c.0}}</td>
      <td>{{c.1}}</td>
      <td>{{c.2}}</td>
      <td>{{c.3}}</td>
      <td>{{c.4}}</td>
      <td>{{c.5}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
</div>  
<br>
<div class="row">
  <div class="col-md-3">
<li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExample3" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-caret-square-o-down"></i>Hasil Akhir</a></li>    
  </div>      
</div>

<div class="collapse" id="collapseExample3">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
   <tr>
    <th>No</th>
    <th>Nama</th>
    <th>Benefit</th>
    <th>Cost</th>
    <th>Rangking</th>
  </tr>
</thead>
<tbody>
  {% for c in akhir %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{c.0}}</td>
    <td>{{c.1}}</td>
    <td>{{c.2}}</td>
    <td>{{c.3}}</td>
  </tr>
  {% endfor %}
</tbody>
</table>

</div>
</div>  
</ul>

PythonMoora/management/hasil_akhir/templates/hasil_akhir/fisika.html
<div class="header text-center"><h3 class="title">Hasil Sleksi Olimpide Sains</h3><p class="category">Kategori Mata Pelajaran <a >Fisika</a></p></div>

<ul class="nav nav-pills nav-stacked">
  <div class="row">
    <div class="col-md-3">
      <li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExamplefis" aria-expanded="false" aria-controls="collapseExamplefis">
        <i class="fa fa-caret-square-o-down"></i>Matrix Awal</a></li>    
      </div>
    </div>

    <div class="collapse" id="collapseExamplefis">
      <div class="well">

       <div align="right">
        <a href="{% url 'hasil_akhir:reporttbl' %}">
         <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
       </a>
     </div>
     <hr>
     <table id="example" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Nilai Akademik</th>
          <th>Karakter</th>
          <th>Pengalaman Lomba</th>
          <th>Hasil Tes</th>
          <th>Kelas</th>
        </tr>
      </thead>
      <tbody>
        {% for c in data_awal %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{c.0}}</td>
          <td>{{c.1}}</td>
          <td>{{c.2}}</td>
          <td>{{c.3}}</td>
          <td>{{c.4}}</td>
          <td>{{c.5}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>  
<!-- ###################################################################### -->
<br>
<div class="row">
  <div class="col-md-3">
    <li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExamplefis1" aria-expanded="false" aria-controls="collapseExamplefis1"><i class="fa fa-caret-square-o-down"></i>Matrix Ternormalisasi</a></li>    
  </div>
</div>

<div class="collapse" id="collapseExamplefis1">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Nama</th>
      <th>Nilai Akademik</th>
      <th>Karakter</th>
      <th>Pengalaman Lomba</th>
      <th>Hasil Tes</th>
      <th>Kelas</th>
    </tr>
  </thead>
  <tbody>
    {% for c in ternormalisasi %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{c.0}}</td>
      <td>{{c.1}}</td>
      <td>{{c.2}}</td>
      <td>{{c.3}}</td>
      <td>{{c.4}}</td>
      <td>{{c.5}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
</div>  

<br>

<div class="row">
  <div class="col-md-3">
    <li role="presentation">
      <a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" 
      data-target="#collapseExamplefis2" aria-expanded="false" aria-controls="collapseExamplefis2">
      <i class="fa fa-caret-square-o-down"></i>Matrix Pembobotan</a></li>    
    </div>
  </div>

  <div class="collapse" id="collapseExamplefis2">
    <div class="well">

     <div align="right">
      <a href="{% url 'hasil_akhir:reporttbl' %}">
       <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
     </a>
   </div>
   <hr>
   <table id="example" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Nilai Akademik</th>
        <th>Karakter</th>
        <th>Pengalaman Lomba</th>
        <th>Hasil Tes</th>
        <th>Kelas</th>
      </tr>
    </thead>
    <tbody>
      {% for c in pembobotan %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{c.0}}</td>
        <td>{{c.1}}</td>
        <td>{{c.2}}</td>
        <td>{{c.3}}</td>
        <td>{{c.4}}</td>
        <td>{{c.5}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
</div>  
<br>

<div class="row">
  <div class="col-md-3">
    <li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExamplefis3" aria-expanded="false" aria-controls="collapseExamplefis3"><i class="fa fa-caret-square-o-down"></i>Hasil Akhir</a></li>    
  </div>
</div>

<div class="collapse" id="collapseExamplefis3">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
   <tr>
    <th>No</th>
    <th>Nama</th>
    <th>Benefit</th>
    <th>Cost</th>
    <th>Rangking</th>
  </tr>
</thead>
<tbody>
  {% for c in akhir %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{c.0}}</td>
    <td>{{c.1}}</td>
    <td>{{c.2}}</td>
    <td>{{c.3}}</td>
  </tr>
  {% endfor %}
</tbody>
</table>

</div>
</div>  
</ul>

PythonMoora/management/hasil_akhir/templates/hasil_akhir/index.html
{% extends 'layout/dashboard/index.html' %} {% block content %}
<div class="content-wrapper">
    <section class="content-header">
        <h1>
           Hasil Olimpiade Sains
       </h1>
       <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Hasil Matrix</a></li>
        <li class="active">Mata Pelajaran</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div id="contoh">
                <ul class="nav nav-tabs">
                    <li><a href="{% url 'hasil_akhir:biologi' %}">Biologi</a></li>
                    <li><a href="{% url 'hasil_akhir:fisika' %}">Fisika</a></li>
                    <li><a href="{% url 'hasil_akhir:kimia' %}">Kimia</a></li>
                    <li><a href="{% url 'hasil_akhir:matematika' %}">Matematika</a></li>
                </ul>
            </div>
           
                </div>
            </div>
        </section>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#example1').DataTable( {
                "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50,]]
            } );
        } );
    </script>
    <script>
      $('#contoh').tabs();
  </script>
  {% endblock %}

PythonMoora/management/hasil_akhir/templates/hasil_akhir/kimia.html
<div class="header text-center"><h3 class="title">Hasil Sleksi Olimpide Sains</h3><p class="category">Kategori Mata Pelajaran <a >Matematika</a></p></div>

<ul class="nav nav-pills nav-stacked">
  <div class="row">
    <div class="col-md-3">
      <li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExamplekim" aria-expanded="false" aria-controls="collapseExamplekim">
        <i class="fa fa-caret-square-o-down"></i>Matrix Awal</a></li>    
      </div>
    </div>
  <div class="collapse" id="collapseExamplekim">
    <div class="well">

     <div align="right">
      <a href="{% url 'hasil_akhir:reporttbl' %}">
       <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
     </a>
   </div>
   <hr>
   <table id="example" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Nilai Akademik</th>
        <th>Karakter</th>
        <th>Pengalaman Lomba</th>
        <th>Hasil Tes</th>
        <th>Kelas</th>
      </tr>
    </thead>
    <tbody>
      {% for c in data_awal %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{c.0}}</td>
        <td>{{c.1}}</td>
        <td>{{c.2}}</td>
        <td>{{c.3}}</td>
        <td>{{c.4}}</td>
        <td>{{c.5}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
</div>
<br>  
<!-- ###################################################################### -->
<div class="row">
    <div class="col-md-3">
      <li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExamplekim1" aria-expanded="false" aria-controls="collapseExamplekim1">
        <i class="fa fa-caret-square-o-down"></i>Matrix Ternormalisasi</a></li>    
      </div>
    </div>
<div class="collapse" id="collapseExamplekim1">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Nama</th>
      <th>Nilai Akademik</th>
      <th>Karakter</th>
      <th>Pengalaman Lomba</th>
      <th>Hasil Tes</th>
      <th>Kelas</th>
    </tr>
  </thead>
  <tbody>
    {% for c in ternormalisasi %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{c.0}}</td>
      <td>{{c.1}}</td>
      <td>{{c.2}}</td>
      <td>{{c.3}}</td>
      <td>{{c.4}}</td>
      <td>{{c.5}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
</div>  
<br>
<div class="row">
    <div class="col-md-3">
      <li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExamplekim2" aria-expanded="false" aria-controls="collapseExamplekim2">
        <i class="fa fa-caret-square-o-down"></i>Matrix Pembobotan</a></li>    
      </div>
    </div>
<div class="collapse" id="collapseExamplekim2">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>No</th>
      <th>Nama</th>
      <th>Nilai Akademik</th>
      <th>Karakter</th>
      <th>Pengalaman Lomba</th>
      <th>Hasil Tes</th>
      <th>Kelas</th>
    </tr>
  </thead>
  <tbody>
    {% for c in pembobotan %}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{c.0}}</td>
      <td>{{c.1}}</td>
      <td>{{c.2}}</td>
      <td>{{c.3}}</td>
      <td>{{c.4}}</td>
      <td>{{c.5}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
</div>  
<br>
<div class="row">
    <div class="col-md-3">
      <li role="presentation"><a class="btn btn-block btn-social btn-facebook" type="button" data-toggle="collapse" data-target="#collapseExamplekim3" aria-expanded="false" aria-controls="collapseExamplekim3">
        <i class="fa fa-caret-square-o-down"></i>Hasil Akhir</a></li>    
      </div>
    </div>
<div class="collapse" id="collapseExamplekim3">
  <div class="well">

   <div align="right">
    <a href="{% url 'hasil_akhir:reporttbl' %}">
     <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
   </a>
 </div>
 <hr>
 <table id="example" class="table table-bordered table-striped">
  <thead>
   <tr>
    <th>No</th>
    <th>Nama</th>
    <th>Benefit</th>
    <th>Cost</th>
    <th>Rangking</th>
  </tr>
</thead>
<tbody>
  {% for c in akhir %}
  <tr>
    <td>{{forloop.counter}}</td>
    <td>{{c.0}}</td>
    <td>{{c.1}}</td>
    <td>{{c.2}}</td>
    <td>{{c.3}}</td>
  </tr>
  {% endfor %}
</tbody>
</table>

</div>
</div>  
</ul>

PythonMoora/management/hasil_akhir/templates/hasil_akhir/tabelLama.html
<div class="box">
    <div class="box-body">
        <div class="box-header">
            <h3 class="box-title">Matrix Ternormalisasi Biologi</h3>
            
            <div align="right">
                <a href="{% url 'hasil_akhir:reporttbl' %}">
                   <button class="btn btn-info"><i class="fa fa-print"></i> Print</button>
                </a>
            </div>
        </div>
        <table id="example" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama</th>
                    <th>Nilai Akademik</th>
                    <th>Karakter</th>
                    <th>Pengalaman Lomba</th>
                    <th>Hasil Tes</th>
                    <th>Kelas</th>
                </tr>
            </thead>
            <tbody>
                {% for c in nl %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{c.0}}</td>
                    <td>{{c.1}}</td>
                    <td>{{c.2}}</td>
                    <td>{{c.3}}</td>
                    <td>{{c.4}}</td>
                    <td>{{c.5}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
</div>
    </div>
</section>
</div>

<script type="text/javascript">
$('#example').DataTable();
</script>