PythonMoora/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from app.config import setting
from login import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^login/', include('login.urls', namespace='login')),
    # url(r'^', views.LoginView.as_view(), name='login'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^dologin/$', views.AksiLoginView.as_view(), name='dologin'),
    url(r'^dologout/$', views.AksiLogoutView.as_view(), name='dologout'),

    url(r'^siswa/', include('management.siswa.urls', namespace='siswa')),
    url(r'^kelas/', include('management.kelas.urls', namespace='kelas')),
    url(r'^bobot/', include('management.bobot.urls', namespace='bobot')),
    url(r'^hasiltes/', include('management.hasiltes.urls', namespace='hasiltes')),
    url(r'^nilai_akademik/', include('management.nilai_akademik.urls', namespace='nilai_akademik')),
    url(r'^karakter/', include('management.karakter.urls', namespace='karakter')),
    url(r'^plomba/', include('management.plomba.urls', namespace='plomba')),
    url(r'^hasil_akhir/', include('management.hasil_akhir.urls', namespace='hasil_akhir')),
    url(r'^tesolimpiade/', include('tesolimpiade.urls', namespace='tesolimpiade')),


]

urlpatterns +=  staticfiles_urlpatterns()
urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

PythonMoora/tesolimpiade/urls.py
from django.conf.urls import url
from tesolimpiade import views

urlpatterns = [
    url (r'^$', views.ListTesOlimpiadeView.as_view(), name='view'),
    url(r'^simpan/$', views.SimpanHasilTesView.as_view(), name='simpan'),

    # url (r'^soal$', views.ListTesOlimpiadeSoalView.as_view(), name='soal'),
    # url (r'^add_olimpiade$', views.AddOlimpiadeView.as_view(), name='add_olimpiade'),
]

PythonMoora/templates/layout/dashboard/css.html
{% load staticfiles %}

<!-- css -->
<link rel="stylesheet" href="{% static 'components/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'components/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'components/admin-lte/dist/css/AdminLTE.css' %}">
<link rel="stylesheet" href="{% static 'components/admin-lte/dist/css/skins/_all-skins.min.css' %}">
<link rel="stylesheet" href="{% static 'components/datatables.net-bs/css/dataTables.bootstrap.css' %}">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

PythonMoora/templates/layout/dashboard/footer.html
  <footer class="main-footer">
    <div class="container">
      
      <strong>Copyright © 2017-2018 <a>@yunuslon</a>.</strong> Metode Moora.
    </div>
    <!-- /.container -->
  </footer>

PythonMoora/templates/layout/dashboard/head.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Document</title>

{% include 'layout/dashboard/css.html' %}
{% include 'layout/dashboard/js.html' %}

PythonMoora/templates/layout/dashboard/header.html
<header class="main-header">
  <!-- Logo -->
  <a href="../../index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>SPK</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>SPK MOORA</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li>
          <a href="#">
            <i class="fa fa-power-off"> Log out 
            </i>
          </a>
        </li>
      </ul>
    </div>
</nav>
</header>

PythonMoora/templates/layout/dashboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% include 'layout/dashboard/head.html' %}
</head>
<body class="skin-purple fixed sidebar-mini sidebar-mini-expand-feature sidebar-open" 
style="height: auto; min-height: 100%;">
    {% include 'layout/dashboard/header.html' %}
    {% include 'layout/dashboard/sidebar.html' %}    
    {% block content %} {% endblock %}     
    {% include 'layout/dashboard/footer.html' %}    
</body>
</html>

PythonMoora/templates/layout/dashboard/js.html
{% load staticfiles %}

<!-- jQuery -->
<script src="{%  static 'components/jquery/dist/jquery.js' %}"></script>
<script src="{%  static 'components/jquery/dist/jquery.min.js' %}"></script>
<script src="{%  static 'components/fastclick/lib/fastclick.js' %}"></script>
<script src="{%  static 'components/jquery-ui/jquery-ui.js' %}"></script>
<script src="{%  static 'components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{%  static 'components/jquery-slimscroll/jquery.slimscroll.js' %}"></script>
<script src="{%  static 'components/admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{%  static 'components/admin-lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{%  static 'components/admin-lte/plugins/iCheck/icheck.min.js' %}"></script>
<script src="{%  static 'components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{%  static 'components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{%  static 'components/admin-lte/dist/js/adminlte.js' %}"></script>
<script src="{%  static 'components/admin-lte/dist/js/demo.js' %}"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>


<script>
    $(function () {
      $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
        checkboxClass: 'icheckbox_minimal-blue',
        radioClass   : 'iradio_minimal-blue',
        increaseArea : '20%' //optional
      })
    })
</script>

PythonMoora/templates/layout/dashboard/sidebar.html
{% load staticfiles %}
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MAIN NAVIGATION</li>
      <li class="header"></li>
      <li>
        <a href="{% url 'admin:index' %}">
          <i class="fa fa-user"></i> Admin Site</a>

        </li>
        <!-- <li class="header"></li> -->

        <li><a href="{% url 'bobot:view' %}">  <i class="fa fa-gears"></i> Bobot</a></li>
        <!-- <li class="header"></li> -->

        <li class="treeview active menu-open">
          <a href="#">
            <i class="fa fa-database"></i>
            <span>Data Siswa</span>
          </a>
          <ul class="treeview-menu">    
            <li><a href="{% url 'siswa:view' %}"><i class="fa fa-circle-o"></i>Siswa</a></li>
            <li><a href="{% url 'nilai_akademik:view' %}"><i class="fa fa-circle-o"></i>Nilai Akademik</a></li>
            <li><a href="{% url 'karakter:view' %}"><i class="fa fa-circle-o"></i>Karakter</a></li>
            <li><a href="{% url 'plomba:view' %}"><i class="fa fa-circle-o"></i>Pengalaman Lomba</a></li>
            <li><a href="{% url 'hasiltes:view' %}"><i class="fa fa-circle-o"></i>Hasil Tes</a></li>
            <li><a href="{% url 'kelas:view' %}"><i class="fa fa-circle-o"></i>Kelas</a></li>
          </ul>
        </li>
        <li><a href="{% url 'hasil_akhir:view' %}">  <i class="fa fa-mortar-board"></i> Mata Pelajaran</a></li>
        
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>


  