PythonMoora/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from app.config import setting
from login import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^login/', include('login.urls', namespace='login')),
    # url(r'^', views.LoginView.as_view(), name='login'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^dologin/$', views.AksiLoginView.as_view(), name='dologin'),
    url(r'^dologout/$', views.AksiLogoutView.as_view(), name='dologout'),

    url(r'^siswa/', include('management.siswa.urls', namespace='siswa')),
    url(r'^kelas/', include('management.kelas.urls', namespace='kelas')),
    url(r'^bobot/', include('management.bobot.urls', namespace='bobot')),
    url(r'^hasiltes/', include('management.hasiltes.urls', namespace='hasiltes')),
    url(r'^nilai_akademik/', include('management.nilai_akademik.urls', namespace='nilai_akademik')),
    url(r'^karakter/', include('management.karakter.urls', namespace='karakter')),
    url(r'^plomba/', include('management.plomba.urls', namespace='plomba')),
    url(r'^hasil_akhir/', include('management.hasil_akhir.urls', namespace='hasil_akhir')),
    url(r'^tesolimpiade/', include('tesolimpiade.urls', namespace='tesolimpiade')),


]

urlpatterns +=  staticfiles_urlpatterns()
urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

PythonMoora/management/nilai_akademik/urls.py
from django.conf.urls import url
from management.nilai_akademik import views

urlpatterns = [
    url (r'^$', views.ListNilaiAkademikView.as_view(), name='view'),
    url(r'^edit/(?P<id>\d+)$', views.EditNilaiAkademikView.as_view(), name='edit'),
	url(r'^simpan/$', views.SaveNilaiAkademikView.as_view(), name='simpan'),
	url(r'^update/$', views.UpdateNilaiAkademikView.as_view(), name='update'),
	url(r'^hapus/(?P<id>\d+)$', views.HapusNilaiAkademikView.as_view(), name='hapus'),
    
]

PythonMoora/management/nilai_akademik/models.py
from django.db import models

# Create your models here.

PythonMoora/management/nilai_akademik/forms.py
from django import forms
from orm.models import NilaiAkademik,Siswa
# from django.contrib.auth.models import User


class NilaiAkdemikForm(forms.Form):
    id = forms.CharField(required=False, widget=forms.HiddenInput())
    mata_pelajaran = forms.CharField(max_length=30)
    nilai = forms.IntegerField( required=False, initial=0)
    siswa_all = Siswa.objects.all()
    siswa = forms.ModelChoiceField(queryset=siswa_all, initial=0) 
    
    
    # user = forms.CharField(User, initial=0)
    class Meta:
        model = NilaiAkademik

PythonMoora/management/nilai_akademik/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.views.generic import View
from django.http import HttpResponse
from django.contrib import messages
from orm.models import NilaiAkademik,Siswa
from .forms import NilaiAkdemikForm
# Create your views here.

class ListNilaiAkademikView(View):
    def get(self, request):
        template = 'nilai_akademik/index.html'

        form = NilaiAkdemikForm(request.POST or None)
        nilai_akademik = NilaiAkademik.objects.all()
        data = {
            'form'  : form,
            'siswa' : Siswa.objects.all(),
            'nilai_akademik' : nilai_akademik,
        }
        return render(request, template, data)


class SaveNilaiAkademikView(View):
    def post(self, request):
        template = 'nilai_akademik/index.html'
        form = NilaiAkdemikForm(request.POST or None)
        if form.is_valid():
            
            nilaiakademik = NilaiAkademik()
            nilaiakademik.siswa = form.cleaned_data['siswa']
            nilaiakademik.mata_pelajaran = form.cleaned_data['mata_pelajaran']
            nilaiakademik.nilai = form.cleaned_data['nilai']
            messages.add_message(request, messages.INFO, 'Data Berhasil Disimpan')   
            nilaiakademik.save()
            return redirect('nilai_akademik:view')
        else:
            nilaiakademik = NilaiAkademik.objects.all()
            data = {
                'form': form,
                'nilaiakademik': nilaiakademik,
            }
            messages.add_message(request, messages.INFO, 'Data Gagal Disimpan !!')               
            return render(request, template, data)


class EditNilaiAkademikView(View):
    template = 'nilai_akademik/edit.html'

    def get(self, request, id):
        nilai_akademik = NilaiAkademik.objects.filter(id=id)
        if not nilai_akademik.exists():
            return redirect('nilai_akademik:view')
        nilai_akademik = nilai_akademik.first()
        initial = {

            'id': nilai_akademik.id,
            'mata_pelajaran': nilai_akademik.mata_pelajaran,
            'nilai': nilai_akademik.nilai,
            'siswa': nilai_akademik.siswa,
        }

        form = NilaiAkdemikForm(initial=initial)
        nilai_akademik = NilaiAkademik.objects.all()
        data = {
            'id':id,
            'form': form,
            'form_mode' : 'edit',
            'nilaiakademik' : nilai_akademik,
        }
        return render(request, self.template, data)


class UpdateNilaiAkademikView(View):

    def post(self, request):
        
        template = "nilai_akademik/index.html"
        form = NilaiAkdemikForm(request.POST or None)
        if form.is_valid():
            id = form.cleaned_data['id']
            nilai_akademik = NilaiAkademik.objects.get(pk=id)
            nilai_akademik.siswa = form.cleaned_data['siswa']
            nilai_akademik.mata_pelajaran = form.cleaned_data['mata_pelajaran']
            nilai_akademik.nilai = form.cleaned_data['nilai']
            messages.add_message(request, messages.INFO, 'Data Berhasil Diupdate')               
            nilai_akademik.save(force_update=True)
            return redirect('nilai_akademik:view')
        else:
            nilai_akademik = NilaiAkademik.objects.all()
            data    =  {
                'form_mode':'edit',
                'form': form,
                'nilai_akademik': nilai_akademik,
            }
            messages.add_message(request, messages.INFO, 'Data Gagal Diupdate !!')                           
            return render(request, template, data)




class HapusNilaiAkademikView(View):
    
    def get(self, request, id):
        nilaiakademik = NilaiAkademik.objects.filter(id=id)
        if nilaiakademik.exists():
            nilaiakademik.first().delete()
            messages.add_message(request, messages.INFO, 'Data Berhasil Dihapus')                                       
            return redirect('nilai_akademik:view')
        else:
            messages.add_message(request, messages.INFO, 'Data Gagal Dihapus !!')      

PythonMoora/management/nilai_akademik/templates/nilai_akademik/edit.html
{% extends 'layout/dashboard/index.html' %} 
{% load widget_tweaks %}
{% block content %}

<div class="content-wrapper">
  <section class="content-header">
    <h1>
      Nilai Akademik
      <small>Template</small>
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="#">
          <i class="fa fa-dashboard"></i> Nilai Akademik</a>
        </li>
        <li class="active">Template</li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="box box-success">
            <div class="box-header with-border">
              Edit Nilai Akademik
            </div>
            <div class="box-body">

              <div class="col-md-12 col-sm-9">
                <form  role="form" action="{% url 'nilai_akademik:update' %}" method="POST"> 
                  <input type="hidden" name="id" value="{{id}}" class="form-control">
                  {% csrf_token %}
                  <div class="box-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1" class="control-label">Siswa</label>
                      {{form.siswa | add_class:"form-control" }}
                    </div>
                  </div>

                  <div class="box-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1" class="control-label">Olimpiade</label>
                      <select class="form-control " name="mata_pelajaran" >
                        <option selected="selected">Pilih Olimpiade</option>
                        <option value="biologi">Biologi</option>
                        <option value="matematika">Matematika</option>
                        <option value="fisika">Fisika</option>
                        <option value="kimia">Kimia</option>
                      </select>
                    </div>
                  </div>

                  <div class="box-body" >
                    <div class="form-group">
                      <label for="exampleInputEmail1" class="control-label">Nilai</label>
                      <div id="test" >
                        {{form.nilai | add_class:"form-control" |append_attr:"placeholder:Input Nilai" }}
                      </div>
                    </div>
                  </div>

                  

                  <!-- /.box-body -->            
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">

                      <i class="fa fa-refresh" aria-hidden="true"></i> Update
                    </button>
                  </div>
                </form>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>



{% endblock %}

PythonMoora/management/nilai_akademik/templates/nilai_akademik/index.html
{% extends 'layout/dashboard/index.html' %} {% block content %}
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Data
            <small>Nilai Akademik</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Nilai Akademik</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-sm-12">
                {% include 'nilai_akademik/table.html' %}
            </div>
        </div>
    </section>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example1').DataTable( {
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50,]]
        } );
    } );
</script>
{% endblock %}

PythonMoora/management/nilai_akademik/templates/nilai_akademik/table.html
{% load widget_tweaks %}
<div class="box">
  <div class="box-body">

    <div class="box-header">

     <!-- <h3 class="box-title">Kelas</h3> -->
     <a type="button" class="btn btn-info" data-toggle="modal" data-target="#modal-defaultna"> 
       Tambah <i class="fa fa-plus"></i> 
     </a>
        </button>



   </div>
   <table id="example1" class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>No</th>
        <th>Nama</th>
        <th>Nilai</th>
        <th>Olimpiade</th>
        <th>Aksi</th>

      </tr>
    </thead>
    <tbody>
      {% for nl in nilai_akademik %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>{{nl.siswa.nama}}</td>
        <td>{{nl.nilai}}</td>
        <td>{{nl.mata_pelajaran}}</td>
          <td>

           <a href="{% url 'nilai_akademik:edit' nl.id %}" class="btn btn-warning">
            <i class="fa fa-edit"></i>
          </a>
          <button class="btn btn-danger" data-toggle="modal" data-target="#myModal{{nl.id}}">
            <i class="fa fa-trash"></i>
          </button>

          <!-- Modal -->
          <div class="modal fade" id="myModal{{nl.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-md" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Konfirmasi Penghapusan</h4>
                </div>
                <div class="modal-body">
                  Apakah anda yakin ingin menghapus Siswa dengan nama <b>{{nl.siswa.nama}}</b> dan id <b>{{nl.id}}</b>?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                  <a href="{% url 'nilai_akademik:hapus' id=nl.id %}" class="btn btn-danger">
                    <i class="fa fa-trash"></i> Hapus
                  </a>
                </div>
              </div>
            </div>
          </div>
          <!-- Modal -->
        </td>
      </tr>


      {% endfor %}

    </tbody>
  </table>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-defaultna">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Nilai Akademik</h4>
        </div>
        <div class="modal-body">
          <!-- <p>One fine body&hellip;</p> -->
          <div class="box box-danger">
            <div class="box-header">
              <h3 class="box-title">Input Data Kelas</h3>
            </div>
            <div class="box-body">
              <!-- Date dd/mm/yyyy -->
              <form method="POST" action="{% url 'nilai_akademik:simpan'%}">
                {% csrf_token %}

                <div class="form-group">
                  <label>Nama Siswa</label>
                  <div class="input-group">
                   <div class="input-group-addon">
                    <i class="fa fa-user"></i>
                  </div>
                  {{form.siswa | add_class:"form-control" |append_attr:"placeholder:Input Siswa"}}

                </div>
              </div>
              <br>

              <div class="form-group">
                <label>Olimpiade</label>

                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-mortar-board"></i>
                  </div>

                  <select class="form-control " name="mata_pelajaran" >
                    <option selected="selected">Pilih Olimpiade</option>
                    <option value="biologi">Biologi</option>
                    <option value="matematika">Matematika</option>
                    <option value="fisika">Fisika</option>
                    <option value="kimia">Kimia</option>
                  </select>
                </div>
                <!-- /.input group -->
              </div>


              <div class="form-group">
                <label>Nilai</label>

                <div class="input-group">
                  <div class="input-group-addon">
                  </div>
                  <!-- <input type="text" class="form-control" name="nilai" id="id_nilai" value=""> -->
                  <input type="text" class="form-control" name="nilai"  value="">
                </div>
                <!-- /.input group -->
              </div>


            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
          <button class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
  {% if messages %}
  {% for message in messages %}
  <script>
    toastr.success('{{message}}')
  </script>
  {% endfor %}
  {% endif %}
</div>
<!-- /.modal -->