PythonMoora/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from app.config import setting
from login import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^login/', include('login.urls', namespace='login')),
    # url(r'^', views.LoginView.as_view(), name='login'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^dologin/$', views.AksiLoginView.as_view(), name='dologin'),
    url(r'^dologout/$', views.AksiLogoutView.as_view(), name='dologout'),

    url(r'^siswa/', include('management.siswa.urls', namespace='siswa')),
    url(r'^kelas/', include('management.kelas.urls', namespace='kelas')),
    url(r'^bobot/', include('management.bobot.urls', namespace='bobot')),
    url(r'^hasiltes/', include('management.hasiltes.urls', namespace='hasiltes')),
    url(r'^nilai_akademik/', include('management.nilai_akademik.urls', namespace='nilai_akademik')),
    url(r'^karakter/', include('management.karakter.urls', namespace='karakter')),
    url(r'^plomba/', include('management.plomba.urls', namespace='plomba')),
    url(r'^hasil_akhir/', include('management.hasil_akhir.urls', namespace='hasil_akhir')),
    url(r'^tesolimpiade/', include('tesolimpiade.urls', namespace='tesolimpiade')),


]

urlpatterns +=  staticfiles_urlpatterns()
urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

PythonMoora/management/karakter/urls.py
from django.conf.urls import url
from management.karakter import views

urlpatterns = [
    url (r'^$', views.ListKarakterView.as_view(), name='view'),
    url(r'^edit/(?P<id>\d+)$', views.EditKarakterView.as_view(), name='edit'),
	url(r'^simpan/$', views.SaveKarakterView.as_view(), name='simpan'),
	url(r'^update/$', views.UpdateKarakterView.as_view(), name='update'),
	url(r'^hapus/(?P<id>\d+)$', views.HapusKarakterView.as_view(), name='hapus'),

]

PythonMoora/management/karakter/models.py
from django.db import models

# Create your models here.

PythonMoora/management/karakter/forms.py
from django import forms
from orm.models import Karakter,Siswa
# from django.contrib.auth.models import User


class KarakterForm(forms.Form):
    id = forms.CharField(required=False, widget=forms.HiddenInput())
    mata_pelajaran = forms.CharField(max_length=30)
    sikap = forms.CharField(max_length=30)
    nilai = forms.IntegerField( required=False, initial=0)
    siswa_all = Siswa.objects.all()
    siswa = forms.ModelChoiceField(queryset=siswa_all, initial=0) 
    
    
    class Meta:
        model = Karakter

PythonMoora/management/karakter/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.views.generic import View
from django.http import HttpResponse
from django.contrib import messages
from orm.models import Karakter, Siswa
from .forms import KarakterForm
# Create your views here.

class ListKarakterView(View):
    def get(self, request):
        template = 'karakter/index.html'
        karakter = Karakter.objects.all()
        form = KarakterForm(request.POST or None)
        data = {
            'form' : form,
            'karakter' : karakter,
            'siswa' : Siswa.objects.all(),
        }
        return render(request, template, data)


class SaveKarakterView(View):
    def post(self, request):
        template = 'karakter/index.html'
        form = KarakterForm(request.POST or None)
        if form.is_valid():
            
            karakter = Karakter()
            karakter.siswa = form.cleaned_data['siswa']
            karakter.mata_pelajaran = form.cleaned_data['mata_pelajaran']
            karakter.sikap = form.cleaned_data['sikap']
            karakter.nilai = form.cleaned_data['nilai']
            messages.add_message(request, messages.INFO, 'Data Berhasil Disimpan')   
            karakter.save()
            return redirect('karakter:view')
        else:
            karakter = Karakter.objects.all()
            data = {
                'form': form,
                'karakter': karakter,
            }
            messages.add_message(request, messages.INFO, 'Data Gagal Disimpan !!')               
            return render(request, template, data)


class EditKarakterView(View):
    template = 'karakter/edit.html'

    def get(self, request, id):
        karakter = Karakter.objects.filter(id=id)
        if not karakter.exists():
            return redirect('karakter:view')
        karakter = karakter.first()
        initial = {

            'id': karakter.id,
            'mata_pelajaran': karakter.mata_pelajaran,
            'sikap': karakter.sikap,
            'nilai': karakter.nilai,
            'siswa': karakter.siswa,
        }

        form = KarakterForm(initial=initial)
        karakter = Karakter.objects.all()
        data = {
            'id':id,
            'form': form,
            'form_mode' : 'edit',
            'karakter' : karakter,
        }
        return render(request, self.template, data)


class UpdateKarakterView(View):

    def post(self, request):
        
        template = "karakter/index.html"
        form = KarakterForm(request.POST or None)
        if form.is_valid():
            id = form.cleaned_data['id']
            karater = Karakter.objects.get(pk=id)
            karater.siswa = form.cleaned_data['siswa']
            karater.mata_pelajaran = form.cleaned_data['mata_pelajaran']
            karater.sikap = form.cleaned_data['sikap']
            karater.nilai = form.cleaned_data['nilai']
            messages.add_message(request, messages.INFO, 'Data Berhasil Diupdate')               
            karater.save(force_update=True)
            return redirect('karakter:view')
        else:
            karater = Karakter.objects.all()
            data    =  {
                'form_mode':'edit',
                'form': form,
                'karakter': karater,
            }
            messages.add_message(request, messages.INFO, 'Data Gagal Diupdate !!')                           
            return render(request, template, data)




class HapusKarakterView(View):
    
    def get(self, request, id):
        karakter = Karakter.objects.filter(id=id)
        if karakter.exists():
            karakter.first().delete()
            messages.add_message(request, messages.INFO, 'Data Berhasil Dihapus')                                       
            return redirect('karakter:view')
        else:
            messages.add_message(request, messages.INFO, 'Data Gagal Dihapus !!')      

PythonMoora/management/karakter/templates/karakter/edit.html
{% extends 'layout/dashboard/index.html' %} 
{% load widget_tweaks %}
{% block content %}

<div class="content-wrapper">
  <section class="content-header">
    <h1>
      Karakter
      <small>Template</small>
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="#">
          <i class="fa fa-dashboard"></i> Karakter</a>
        </li>
        <li class="active">Template</li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="box box-success">
            <div class="box-header with-border">
              Edit Data Karakter
            </div>
            <div class="box-body">

              <div class="col-md-12 col-sm-9">
                <form  role="form" action="{% url 'karakter:update' %}" method="POST"> 
                  <input type="hidden" name="id" value="{{id}}" class="form-control">
                  {% csrf_token %}
                  <div class="box-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1" class="control-label">Siswa</label>
                      {{form.siswa | add_class:"form-control" }}
                    </div>
                  </div>

                  <div class="box-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1" class="control-label">Olimpiade</label>
                      <select class="form-control " name="mata_pelajaran" >
                        <option selected >Pilih Olimpiade</option>
                        <option value="biologi" >Biologi</option>
                        <option value="matematika">Matematika</option>
                        <option value="fisika">Fisika</option>
                        <option value="kimia">Kimia</option>
                      </select>
                    </div>
                  </div>

                   <div class="box-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1" class="control-label">Sikap</label>
                      <select class="form-control " name="sikap" id="id_sikap" onclick="sleksi()">
                        <option selected="selected">Pilih Sikap</option>
                        <option >Baik</option>
                        <option >Cukup Baik</option>
                        <option >Buruk</option>
                      </select>
                    </div>
                  </div>

                  <div class="box-body" hidden >
                    <div class="form-group">
                      <label for="exampleInputEmail1" class="control-label">Nilai</label>
                      <div >
                        {{form.nilai | add_class:"form-control" |append_attr:"id:id_nilai" }}
                      </div>
                    </div>
                  </div>

                  

                  <!-- /.box-body -->            
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">

                      <i class="fa fa-refresh" aria-hidden="true"></i> Update
                    </button>
                  </div>
                </form>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<script>
  
  function sleksi() {
    var a =40 ;
    var b =55 ;
    var c =70 ;
    var d =0;
    var jjg = document.getElementById('id_sikap').value;
    if (jjg === "Baik") {
      document.getElementById("id_nilai").value = c;

    }else if (jjg === "Cukup Baik"){
      document.getElementById("id_nilai").value = b;

    }else if (jjg === "Buruk"){
      document.getElementById("id_nilai").value = a;

    }else {
      document.getElementById("id_nilai").value = d;

    }
  }
</script>



{% endblock %}

PythonMoora/management/karakter/templates/karakter/index.html
{% extends 'layout/dashboard/index.html' %} {% block content %}
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Data
            <small>Karakter</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Karakter</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-sm-12">
                {% include 'karakter/table.html' %}
            </div>
        </div>
    </section>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#example1').DataTable( {
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50,]]
        } );
    } );
</script>
{% endblock %}

PythonMoora/management/karakter/templates/karakter/table.html
{% load widget_tweaks %}

<div class="box">
  <div class="box-body">
    <div class="box-header">
      <a type="button" class="btn btn-info" data-toggle="modal" data-target="#modal-default"> 
       Tambah <i class="fa fa-plus"></i> 
     </a>
    </div>
    <table id="example1" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>sikap</th>
          <th>Olimpiade</th>
          <th>Aksi</th>

        </tr>
      </thead>
      <tbody>
        {% for kl in karakter %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{kl.siswa.nama}}</td>
          <td>{{kl.sikap}}</td>
          <td>{{kl.mata_pelajaran}}</td>
          <td>
            <a href="{% url 'karakter:edit' kl.id %}" class="btn btn-warning">
              <i class="fa fa-edit"></i>
            </a>
            <button class="btn btn-danger" data-toggle="modal" data-target="#myModal{{kl.id}}">
              <i class="fa fa-trash"></i>
            </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal{{kl.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog modal-md" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Konfirmasi Penghapusan</h4>
                  </div>
                  <div class="modal-body">
                    Apakah anda yakin ingin menghapus Siswa dengan nama <b>{{kl.siswa.nama}}</b> dan id <b>{{kl.id}}</b>?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    <a href="{% url 'karakter:hapus' id=kl.id %}" class="btn btn-danger">
                      <i class="fa fa-trash"></i> Hapus
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal -->
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
<!-- #######################################Tambah#################################################################### -->
  <!-- Modal -->
  <div class="modal fade" id="modal-default">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Karakter</h4>
          </div>
          <div class="modal-body">
            <!-- <p>One fine body&hellip;</p> -->
            <div class="box box-danger">
              <div class="box-header">
                <h3 class="box-title">Input Data Karakter Siswa</h3>
              </div>
              <div class="box-body">
                <!-- Date dd/mm/yyyy -->
                <form method="POST" action="{% url 'karakter:simpan'%}">
                  {% csrf_token %}

                  <div class="form-group">
                    <label>Nama Siswa</label>
                    <div class="input-group">
                     <div class="input-group-addon">
                      <i class="fa fa-user"></i>
                    </div>
                    {{form.siswa | add_class:"form-control" |append_attr:"placeholder:Input Siswa"}}

                  </div>
                </div>
                <br>

                <div class="form-group">
                  <label>Sikap</label>

                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-mortar-board"></i>
                    </div>

                    <select class="form-control " name="sikap" id="id_sikap2" onclick="sleksiT()" >
                      <option selected="selected">Sikap Siswa</option>
                      <option>Baik</option>
                      <option>Cukup Baik</option>
                      <option>Buruk</option>
                    </select>
                  </div>
                  <!-- /.input group -->
                </div>
                <br>

                <div class="form-group">
                  <label>Olimpiade</label>

                  <div class="input-group">
                    <div class="input-group-addon">
                      <i class="fa fa-mortar-board"></i>
                    </div>

                    <select class="form-control " name="mata_pelajaran" >
                      <option selected="selected">Pilih Olimpiade</option>
                      <option value="biologi">Biologi</option>
                      <option value="matematika">Matematika</option>
                      <option value="fisika">Fisika</option>
                      <option value="kimia">Kimia</option>
                    </select>
                  </div>
                  <!-- /.input group -->
                </div>


                <div class="form-group" hidden>
                  <label>Nilai</label>

                  <div class="input-group">
                    <div class="input-group-addon">
                    </div>
                    <!-- <input type="text" class="form-control" name="nilai" id="id_nilai" value=""> -->
                    <input type="text" class="form-control" name="nilai" id="id_nilai2" value="">
                  </div>
                  <!-- /.input group -->
                </div>


              </div>
              <!-- /.box-body -->
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
            <button class="btn btn-primary">Save</button>
          </form>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->

  </div>
  <!-- /.modal -->


  <script >

    function sleksiT() {
      var a =40 ;
      var b =55 ;
      var c =70 ;
      var d =0;
      var jjg = document.getElementById('id_sikap2').value;
      if (jjg === "Baik") {
        document.getElementById("id_nilai2").value = c;

      }else if (jjg === "Cukup Baik"){
        document.getElementById("id_nilai2").value = b;

      }else if (jjg === "Buruk"){
        document.getElementById("id_nilai2").value = a;

      }else {
        document.getElementById("id_nilai2").value = d;

      }
    }
  </script>
  {% if messages %}
  {% for message in messages %}
  <script>
    toastr.success('{{message}}')
  </script>
  {% endfor %}
  {% endif %}